# Generated by Django 5.0 on 2026-08-24 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('dairy', '🥛 Dairy'), ('produce', '🥬 Produce'), ('meat', '🥩 Meat'), ('bakery', '🍞 Bakery'), ('snacks', '🍿 Snacks'), ('beverages', '🥤 Beverages'), ('household', '🧹 Household'), ('personal', '🧴 Personal Care'), ('frozen', '❄️ Frozen'), ('other', '📦 Other')], max_length=50)),
                ('season', models.CharField(choices=[('summer', '☀️ Summer'), ('winter', '❄️ Winter'), ('spring', '🌸 Spring'), ('fall', '🍂 Fall'), ('year_round', '🔄 Year Round')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubstituteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['original_item__name', 'substitute_item__name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_categories', models.JSONField(default=list)),
                ('dietary_restrictions', models.JSONField(default=list)),
                ('favorite_brands', models.JSONField(default=list)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_price_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum preferred price', max_digits=10, null=True)),
                ('preferred_price_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum preferred price', max_digits=10, null=True)),
                ('preferred_seasons', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand name of the item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', '💵 USD'), ('EUR', '💶 EUR'), ('GBP', '💷 GBP'), ('INR', '₹ INR')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='dietary_info',
            field=models.JSONField(blank=True, default=dict, help_text='Dietary information like vegan, gluten-free, etc.'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the item', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', '☀️ Summer'), ('winter', '❄️ Winter'), ('spring', '🌸 Spring'), ('fall', '🍂 Fall'), ('year_round', '🔄 Year Round')], help_text='Season when this item is best', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='substitute_for',
            field=models.ForeignKey(blank=True, help_text='This item is a substitute for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutes', to='shopping.item'),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of purchase', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shoppinghistory',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can'), ('box', 'Box'), ('bag', 'Bag'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon')], default='pcs', max_length=10),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['price'], name='shopping_it_price_83d292_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['season'], name='shopping_it_season_a75307_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinghistory',
            index=models.Index(fields=['purchased_at'], name='shopping_sh_purchas_c81eda_idx'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='seasonalitem',
            unique_together={('name', 'season')},
        ),
        migrations.AddField(
            model_name='substituteitem',
            name='original_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_entries', to='shopping.item'),
        ),
        migrations.AddField(
            model_name='substituteitem',
            name='substitute_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_entries', to='shopping.item'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='substituteitem',
            unique_together={('original_item', 'substitute_item')},
        ),
    ]
